### ISSUE TITLE
Windows 7 and older OS Dumps

### ISSUE THREAD

**Issue by ghost** [ergrelet/unlicense#101]
Hi, with the new Recent version of Unlicense, i have some issues running some applications on older Microsoft operative system. Because now, i can only "unpack" an exe from windows 10. (Because of python 11)

This is an issue, now i can't run dumped exes from windows 10 on windows 7, because it requieres a dll called "combase.dll" to initialize the process.

The only solution i had before, its to dump the exe from Windows 7, that would make the file use ucrtbase.dll instead of combase.dll fixing the issue.

I tried running the app from compatibility mode and it didn't make a difference so idk how to fix it

![Screenshot_1](https://github.com/ergrelet/unlicense/assets/94207445/c5286e65-efb6-489d-bf54-1aebbc5f6929)

**Comment by greenozon** [comment]
Have you tried to install python 3.10+  on old good Win7?
there is a repo where guys are still creating compatible installers (as bastards from python community refused to do it)

https://github.com/adang1345/PythonWin7

**Comment by ghost** [comment]
Nop, i'm gonna try it

**Comment by greenozon** [comment]
Using it for last year, no issues so far

![image](https://github.com/ergrelet/unlicense/assets/765343/e0d0ebce-fdf4-4381-b371-2ada85bee987)

**Comment by ghost** [comment]
Ok i tried but i got a lot of issues.
First of all, i can't get visual studio 2022 because w7 doesn't appear to support in anymore, maybe with an older version works but i installed it on W10, compile WinLicense and it didn't work either, i dropped the exe but it throwed an error.
Maybe its a skill issue mine

After that, my idea was to mod the exe to put the W7 version of python38.dll in it, i tried without success, it creates a tmp directory and erases every time it closes, no idea where the DLL is located in the exe so no clue in replacing it.

You just have to replace this dll: [python311.zip](https://github.com/ergrelet/unlicense/files/12470270/python311.zip)
and it should work but i will keep trying.

And BTW the older version didn't work with the new exe that i wanna mod, soo i need the new one instead

**Comment by ghost** [comment]
Ok i found the solution.

Open CFF Explorer and exe, go to Import Directory, search "combase.dll", change the name of combase to "ole32.dll". Save the changes and now the exe should work on Windows 7.
