### ISSUE TITLE
Unable to found IAT

### ISSUE THREAD

**Issue by famouzkk** [ergrelet/unlicense#11]
I'm getting: `ERROR:unlicense.winlicense3:IAT not found.` 
Anything I can do about it? Also it didin't recognize Themide version, so i forced it with  flag. I'm sure its Themida 3, 32bit.

**Comment by ergrelet** [comment]
Hi @famouzkk,
Seems weird, would you be able to share your sample? You can send it to `unlicense@laposte.net`.
Otherwise, having the PE sections layout would help a bit.

**Comment by famouzkk** [comment]
I sent it to you.

**Comment by ergrelet** [comment]
@famouzkk This issue should be fixed with the latest commit.

**Comment by famouzkk** [comment]
My fault, my program is packed with Themida 3.
