### ISSUE TITLE
MemoryError: bad allocation (NetEase, Minecraft.Windows.exe)

### ISSUE THREAD

**Issue by KuromeSan** [ergrelet/unlicense#12]
C:\Users\User\Downloads\2.1.0.159689>py -m unlicense Minecraft.Windows.exe --pause_on_oep
frida-agent: Setting up OEP tracing for "Minecraft.Windows.exe"
frida-agent: Possible OEP (thread #23592): 0x900921e
INFO:unlicense:OEP reached: OEP=0x900921e BASE=0xb40000)
Thread blocked, press ENTER to proceed with the dumping.
ERROR:unlicense.winlicense3:IAT not found

**Comment by KuromeSan** [comment]
file: https://famitama.com/flash/Minecraft.Windows.exe

**Comment by ergrelet** [comment]
Hi, thanks for the report! I'll take a look at this when I have some time.

**Comment by ergrelet** [comment]
I have pushed an update for the IAT search algorithm that fixes issues I had with some of my samples. I haven't had time to check your executable but can you try again with the latest version and see if it fixes your issue as well?

**Comment by KuromeSan** [comment]
Im using the latest commit.

**Comment by ergrelet** [comment]
The latest commit is "d4e69d9690f00477ea4d5ff6f68752012463f47c", have you try with this one in particular?
Anyway, I can't run the executable you linked without having at least some of its dependencies (e.g., `libenvsdk.dll`, `fmod.dll` and `CrashHunter_PC3.dll`) as well.

**Comment by KuromeSan** [comment]
just tried with that commit, and its found the IAP. but now it crashes on "ERROR:unlicense.dump_utils:Failed to fix IAT: Process ID not found"


C:\Users\User\Downloads\2.1.0.159689>py -m unlicense Minecraft.Windows.exe
frida-agent: Setting up OEP tracing for "Minecraft.Windows.exe"
frida-agent: Possible OEP (thread #8364): 0x8a1921e
INFO:unlicense:OEP reached: OEP=0x8a1921e BASE=0x550000)
INFO:unlicense.winlicense3:IAT found: 0xd3bf000
INFO:unlicense.winlicense3:Resolving imports ...
INFO:unlicense.winlicense3:Imports resolved: 1008
INFO:unlicense.winlicense3:Fixed IAT at 0xd3bf000, size=0xbb0
INFO:unlicense.winlicense3:Dumping PE with OEP=0x8a1921e ...
INFO:unlicense.dump_utils:Fixing dump ...
ERROR:unlicense.dump_utils:Failed to fix IAT: Process ID not found

**Comment by KuromeSan** [comment]
here is the full program: http://famitama.com/flash/2.1.0.159689.7z

**Comment by ergrelet** [comment]
Thanks for the upload, I can confirm it goes through on my end. However, it seems only part of the IAT is recovered, I'll have to investigate further but that gets you at least a starting point for static analysis.

The "Process ID not found" error is an unclear message that just means you're trying to dump a 32-bit PE with a 64-bit Python interpreter. That's not supported (by Scylla) at the moment. You should use a 32-bit version of Python to run `unlicense` for the dump to succeed.

I'll push an update that improves the error message in this case.

**Comment by KuromeSan** [comment]
oop
```C:\Users\User\AppData\Local\Programs\Python\Python39-32\python.exe -m unlicense Minecraft.Windows.exe
frida-agent: Setting up OEP tracing for "Minecraft.Windows.exe"
frida-agent: Possible OEP (thread #17572): 0x8e6921e
INFO:unlicense:OEP reached: OEP=0x8e6921e BASE=0x9a0000)
INFO:unlicense.winlicense3:IAT found: 0xd80f000
INFO:unlicense.winlicense3:Resolving imports ...
INFO:unlicense.winlicense3:Imports resolved: 1008
INFO:unlicense.winlicense3:Fixed IAT at 0xd80f000, size=0xbb0
INFO:unlicense.winlicense3:Dumping PE with OEP=0x8e6921e ...
INFO:unlicense.dump_utils:Fixing dump ...
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Downloads\unlicense-main\unlicense\__main__.py", line 4, in <module>
    main()
  File "C:\Users\User\Downloads\unlicense-main\unlicense\application.py", line 19, in main
    fire.Fire(run_unlicense)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39-32\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39-32\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39-32\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\User\Downloads\unlicense-main\unlicense\application.py", line 84, in run_unlicense
    winlicense3.fix_and_dump_pe(process_controller, exe_to_dump,
  File "C:\Users\User\Downloads\unlicense-main\unlicense\winlicense3.py", line 35, in fix_and_dump_pe
    dump_pe(process_controller, pe_file_path, image_base, oep, iat_addr,
  File "C:\Users\User\Downloads\unlicense-main\unlicense\dump_utils.py", line 46, in dump_pe
    _rebuild_pe(output_file_name)
  File "C:\Users\User\Downloads\unlicense-main\unlicense\dump_utils.py", line 63, in _rebuild_pe
    builder.write(pe_file_path)
MemoryError: bad allocation```

it give memory error now

**Comment by ergrelet** [comment]
@KuromeSan Oof, this looks like it's trying to consume too much memory (>2GB). I'll do some profiling and see what can be done.

**Comment by ergrelet** [comment]
@KuromeSan I added a workaround, this only mitigates the issue for now but it seems sufficient in this case. Can you try with the latest commit and if it does it for you?

**Comment by KuromeSan** [comment]
![image](https://user-images.githubusercontent.com/39113159/162420442-63ffcaa2-859a-4026-b945-3e10442f2bd0.png)
YES it works! not only does it unpack but it actually creates a working executable as well!
