### ISSUE TITLE
Universal Windows Platform Applications: - INFO:unlicense.winlicense2:Looking for wrapped imports ...

### ISSUE THREAD

**Issue by KuromeSan** [ergrelet/unlicense#15]
Ulthough in my case i was able to solve this simply by using a win32 varient of the application, i think i should mention that when i tried this on the release version from the microsoft store, i get
"ERROR:unlicense:Failed to automatically detect packer version" error

`C:\Users\User\Downloads>py -m unlicense "C:\Program Files\WindowsApps\Microsoft.MinecraftUWP_1.18.1201.0_x64__8wekyb3d8bbwe\Minecraft.Windows.exe"
ERROR:unlicense:Failed to automatically detect packer version`

i am *guessing* this is because of the fact it is a executable for the Universal Windows Platform.

**Comment by ergrelet** [comment]
Hi @KuromeSan! I've checked the `Microsoft.MinecraftUWP_1.18.1201.0_x64__8wekyb3d8bbwe` package and it seems `Minecraft.Windows.exe` isn't packed in this one?

**Comment by KuromeSan** [comment]
Sorry i meant the Education Edition of the game >-> sorry
can be found here: https://education.minecraft.net/en-us/get-started/download

for some reason, the education edition IS packed: ![image](https://user-images.githubusercontent.com/39113159/162612017-7e69d8fe-0408-4270-a94a-4ecb5400d258.png) which led me to just assuming the main build was as well.

with this, it gets stuck on "INFO:unlicense.winlicense2:Looking for wrapped imports ..."  so it still doesnt work. so the issue is still valid ahah

**Comment by KuromeSan** [comment]
after like a really long time, i got :

ERROR:unlicense.emulation:ERROR: cannot convert 'NoneType' object to bytearray
ERROR:unlicense.emulation:ERROR:
ERROR:unlicense.emulation:ERROR: cannot convert 'NoneType' object to bytearray
ERROR:unlicense.emulation:ERROR:
ERROR:unlicense.emulation:ERROR:
ERROR:unlicense.emulation:ERROR:
ERROR:unlicense.emulation:ERROR:
ERROR:unlicense.emulation:ERROR:
ERROR:unlicense.emulation:ERROR:
ERROR:unlicense.emulation:ERROR:
ERROR:unlicense.emulation:ERROR:
ERROR:unlicense.emulation:ERROR:
ERROR:unlicense.emulation:ERROR:
ERROR:unlicense.emulation:ERROR: cannot convert 'NoneType' object to bytearray
ERROR:unlicense.emulation:ERROR: cannot convert 'NoneType' object to bytearray

**Comment by ergrelet** [comment]
Oh okay thanks for the report, definitely looks like a bug!

**Comment by ergrelet** [comment]
Alright, I finally took some time to take a look at the problem. It's related to #3, because it turns out the section layout doesn't fit what's expected by `unlicense` for executables packed with Themida 2.x.
Also, since this is a 32-bit executable, it's unfortunately expected for import resolution to take a lot of time at the moment (know limitation).
I'll try to get this fixed.

**Comment by ergrelet** [comment]
@KuromeSan The bug is now fixed, however keep in mind that the dumping takes a long time (but eventually finishes successfully.)
