### ISSUE TITLE
failed to load external DLL for DLL unpacking.

### ISSUE THREAD

**Issue by danyhm** [ergrelet/unlicense#21]
Hello,

I tried to unpack a DLL packed with winlicense 2.x and when drag and dropping the DLL into unlicense.exe i get "cannot find xxx.dll please reinstall this application" the xxx.dll is in the same directory as the target dll and I'm running unlicense from the same directory as well.

**Comment by ergrelet** [comment]
Hi! This seems weird, the scenario you describe should indeed be perfectly fine. Are the binaries all of the same bitness (32-bit/64-bit)?

**Comment by danyhm** [comment]
yes, they are all the same bitness. do you need the sample?

**Comment by ergrelet** [comment]
Why not, I can take a look, you can send it to unlicense@proton.me if you want.

**Comment by danyhm** [comment]
Thanks for your time. I sent you the sample.

**Comment by ergrelet** [comment]
The issue seems only happen on the pyinstaller version, so this seems like a bug.

**Comment by danyhm** [comment]
Ok, thanks for letting me know.
and yes it was compiled using delphi. it seems I have to try other options.

**Comment by ergrelet** [comment]
I created two issues that'll be used to track these problems and I'll close this one if you don't mind 😊

**Comment by danyhm** [comment]
sure! thanks! looking forward to the update!

**Comment by imwhite** [comment]
hi, I happened the same issue that "cannot find xxx.dll please reinstall this application"  when i dump dll. how to fix?
