### ISSUE TITLE
ERROR - Original entry point wasn't reached before timeout

### ISSUE THREAD

**Issue by Kurama371** [ergrelet/unlicense#22]
getting the above error, any way to get around that using this tool?

**Comment by ergrelet** [comment]
Hi! Well, this can mean 2 things:
* Either the execution of the target executable is a bit slow and 10s is a bit too short
* Or, the OEP is reached within 10s but it isn't detected by `unlicense`

You can try increasing the timeout value by using the `--timeout` command-line option and see if the problem gets fixed that way. If increasing the timeout doesn't fix this issue then I'd like to have some more information on your sample.

**Comment by Kurama371** [comment]
o/

INFO - Detected packer version: 2.x
frida-agent: Setting up OEP tracing for "sus.exe"
frida-agent: Target module is loaded ...
ERROR - Original entry point wasn't reached before timeout

tried setting the timeout to 30 seconds but still same result. (the gui of the application is open by that time tho)

What kind of information do you need?

**Comment by ergrelet** [comment]
Okay, the OEP isn't detected properly then.
Well, either the sample itself (you can send it to unlicense@proton.me if needed), or at least a hint on what runtime is being used: is it .NET or compiled from C, C++, Delphi or another language and with which compiler (if possible).

**Comment by Kurama371** [comment]
According to Detect It  Easy 3.04:
Compiler: Visual C/C++(12.00.8168)[C++]

**Comment by ergrelet** [comment]
I guess you ran DIE on the packed executable directly? If this is case, this will not show the original executable's information unfortunately. You would have to run DIE on a manual dump.

**Comment by Kurama371** [comment]
I get the same result if i use it on a dumped file created using ollydbg the "themida/winlicense ultra unpacker 1.4" script thats used in various guides, only thing that changes in the scan results of DIE is that its obviously not detecting themida anymore afterwards

**Comment by ergrelet** [comment]
Alright, thanks for the additional information. I'll take a look at what you sent me 👍

**Comment by ergrelet** [comment]
So yes it turns out your sample is compiled from Delphi and its runtime isn't supported, so I'll merge your issue with issue #27 to keep track of that.
