### ISSUE TITLE
[Error] Can`t install unlicense with pyscylla

### ISSUE THREAD

**Issue by pppyo** [ergrelet/unlicense#23]
test@machine:~$ python3 -m pip install unlicense/
Defaulting to user installation because normal site-packages is not writeable
Processing ./unlicense
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting fire<0.5,>=0.4
  Using cached fire-0.4.0.tar.gz (87 kB)
  Preparing metadata (setup.py) ... done
Collecting capstone<5.0,>=4.0
  Using cached capstone-4.0.2-py2.py3-none-manylinux1_x86_64.whl (2.1 MB)
Collecting xxhash<3.0,>=2.0
  Using cached xxhash-2.0.2.tar.gz (64 kB)
  Preparing metadata (setup.py) ... done
**ERROR: Could not find a version that satisfies the requirement pyscylla<0.12.0,>=0.11.0 (from unlicense) (from versions: none)
ERROR: No matching distribution found for pyscylla<0.12.0,>=0.11.0**

**Comment by ergrelet** [comment]
Hi!
`unlicense` can only be used on Windows because the unpacking is done by executing the target executable.

**Comment by molenzwiebel** [comment]
For others encountering this issue that _are_ on Windows, make sure that your Python version is reasonably new. pyscylla v0.11.0 which unlicense currently uses requires Python 3.8 or newer.
