### ISSUE TITLE
Extra sections

### ISSUE THREAD

**Issue by ThePixelGamer** [ergrelet/unlicense#24]
I'm unsure if this is an actual error with unlicense due to my lack of knowledge with themida packed executables but there seems to be some extra sections in the unpacked binary?
![image](https://user-images.githubusercontent.com/15077848/175071641-c3ef504d-0c38-4a2c-b029-dcff690e406c.png)
The data also seems to contain strings that would only exist at runtime.
But feel free to close this if it's not due to unlicense.

**Comment by ergrelet** [comment]
Hi! 
These sections are added by Themida actually. You should also see these in the packed executable.
