### ISSUE TITLE
IAT Being Truncated

### ISSUE THREAD

**Issue by xenocidewiki** [ergrelet/unlicense#31]
I have worked with the tool quite a bit and noticed that the last last nullptr truncation https://github.com/ergrelet/unlicense/blob/d1d545d3659e685479110b4d6464275ff533761d/unlicense/winlicense3.py#L154 tends to cut off a large portions of the IAT in some samples that I've ran it on. I have removed this line in my local copy and it managed to recover everything nicely. Is there a particular reason for why this line is there?

**Comment by ergrelet** [comment]
Hi! First of all, thanks for the feedback!

I noticed this issue recently as well while working on something else and it made me re-read that piece of code. It was originally meant to make things a little bit cleaner by ignoring useless data past the end of the IAT.
The code is actually broken and produces invalid truncations more than anything else.

I've gotten rid of that on the `dev` branch and I'll merge that to `main` later on, after I've fix a few other things.

**Comment by ergrelet** [comment]
This should be fix as of commit e8c7b008bac8eb15a47d1f2c66ff66813b857b1f. This has been merged into `main`.
