### ISSUE TITLE
Failed to automatically detect .text section for 3.x target

### ISSUE THREAD

**Issue by danyhm** [ergrelet/unlicense#35]
Hello,

in my tests, I also found out that for the example program vc_example in the winlicense directory `WinLicenseSDK\ExamplesSDK\Activation\Visual C++`, unlicensed fails to detect the .text section, whereas in PE explorers the .text section is clearly visible

sample protected with the demo version 3.1.3.0
[vc_example_protected.zip](https://github.com/ergrelet/unlicense/files/9175246/vc_example_protected.zip)

**Comment by ergrelet** [comment]
Hi, thanks again for the feedback!
Yes it seems the section layout is a bit different from what I had observed on 3.x executables so far. The version detection and text detection heuristic have to be tweaked a little it seems.

**Comment by ergrelet** [comment]
Alright, I pushed a fix for this issue on `main` 👍

**Comment by danyhm** [comment]
Superb!
