### ISSUE TITLE
Failed to diagnostic signature with Themida

### ISSUE THREAD

**Issue by Pureaznangel** [ergrelet/unlicense#36]
I've got the problem with Themida signature detector, please check with this file.
pass: 123456
https://drive.google.com/file/d/1YUlFyCVnkkgcgbTndEXEAIp5rI3BptGB/view?usp=sharing

**Comment by danyhm** [comment]
the sample is not a valid DLL file. you might have uploaded it incorrectly

**Comment by Pureaznangel** [comment]
Hello, I'm sorry for my mistake, and this is the correct file was packed by Themida that i got the error with unlicense about signature detector when processing: 

https://drive.google.com/file/d/1JfEa59ZrgsQvqeegeuDX8eJDFA1OFoSG/view?usp=sharing

Thanks

**Comment by danyhm** [comment]
unlicense detects this as 3.x target which seems to be correct.
**Warning : the sample seems to be malware **

**Comment by Pureaznangel** [comment]
Not q malware just a paid software, but I need unpack it to find it algo
but, seem unlicense not working on it.

Thanks.

**Comment by Pureaznangel** [comment]
it seems that this software is useless with Themida, no 2.x or 3.x versions work at all. They always return the same OEP and IAT at all.

**Comment by ergrelet** [comment]
The dumping works just fine with version 0.3.0 and the second executable you shared. Closing this issue.
