### ISSUE TITLE
How can I be sure _cinit is not invoked during OEP discovery?

### ISSUE THREAD

**Issue by HybridEidolon** [ergrelet/unlicense#41]
For C++ executables, WinMainCRTStartup is responsible for calling a procedure named _cinit, which initializes all C++ statics prior to calling WinMain.

I have a Winlicense 2 packed EXE which I have unpacking successfully (additionally with support for patching a specific call pattern for imports inside the CRT functions), but when it gets inside _cinit and begins initializing things, it eventually hits a seg fault dereferencing null. My hypothesis is that _cinit may have already been called in the process at this point, and it is running initializers on memory that is in an unexpected state because of it. (Either that, or the location of the static memory is not where it should be, which may be symptomatic of Scylla failing to properly dump and fix the running process)

So, during OEP discovery, is there a way to know for sure that it has not executed any part of the entrypoint by the time it is caught after unpacking?

**Comment by ergrelet** [comment]
Hi! If you're hypothesis is correct, then either the OEP detection failed to detect the actual entrypoint, or `_cinit` was executed as part of the unpacking stub but that would be weird.
Another explanation is that the seg fault comes from some other side effect (and thus would be related to issue #29). I can't know for sure without looking at the sample.

**Comment by HybridEidolon** [comment]
My hypothesis was incorrect and it was in fact issues with import resolution. I don't suspect the unpack stub would ever call _cinit since the consequence of calling it twice is probably not good. I'm gonna go ahead and close.
