### ISSUE TITLE
ERROR - Original entry point wasn't reached before timeout

### ISSUE THREAD

**Issue by fernandon00b** [ergrelet/unlicense#45]
ERROR - Original entry point wasn't reached before timeout 
please help
https://www.dropbox.com/s/bla7juxmigo9zvb/FINAL%202022%20-.exe?dl=0

**Comment by ergrelet** [comment]
Hi! Sorry for the delayed response. The link seems expired unfortunately.

**Comment by fernandon00b** [comment]
https://drive.google.com/file/d/18XlTWoJsTJ1xV7-PXcdpSt7Cuc_9w_Qn/view?usp=sharing

**Comment by ergrelet** [comment]
Can confirm, the OEP isn't detected in this case.

**Comment by fernandon00b** [comment]
will you updated it ?

**Comment by ergrelet** [comment]
Hmm unfortunately this issue is that the original OEP isn't because of WinLicense's licensing check. So basically you won't be able to dump this executable without a valid license for now. Sorry!
