### ISSUE TITLE
ERROR:unlicense.winlicense3:IAT not found

### ISSUE THREAD

**Issue by zhuimengqq** [ergrelet/unlicense#47]
[a12_mini.zip](https://github.com/ergrelet/unlicense/files/9387763/a12_mini.zip)
Erwan Grelet:
           hello,I was try to unpack the 1a.exe, it can not find  IAT (ERROR:unlicense.winlicense3:IAT not found) .are ther has some bugs?

**Comment by ergrelet** [comment]
Hi!

It seems the issue has been fixed on the `main` branch already. If you want to benefit from the fix you'll have to install from the repository with pip or wait for the next release.
