### ISSUE TITLE
ERROR: Invalid parameters

### ISSUE THREAD

**Issue by redxhawk** [ergrelet/unlicense#50]
> ←[1;32mINFO←[0m - Detected packer version: 2.x
> ←[1;36mfrida-agent←[0m: Setting up OEP tracing for "VBAPass.exe"
> ←[1;36mfrida-agent←[0m: Exception handler registered
> ←[1;36mfrida-agent←[0m: OEP found (thread #6816): 0x43ef4f
> ←[1;32mINFO←[0m - OEP reached: OEP=0x43ef4f BASE=0x400000 DOTNET=False
> ←[1;32mINFO←[0m - Looking for wrapped imports ...
> ←[1;32mINFO←[0m - Potential import wrappers found: 828
> ←[1;32mINFO←[0m - Generating exports' hashes, this might take some time ...
> ←[1;32mINFO←[0m - Resolving imports ...
> ←[31;20mERROR - ERROR: invalid parameters←[0m
> ←[31;20mERROR - ERROR: invalid parameters←[0m
> ←[31;20mERROR - ERROR: invalid parameters←[0m
> ←[31;20mERROR - ERROR: invalid parameters←[0m
> ←[1;32mINFO←[0m - Imports resolved: 244
> ←[1;32mINFO←[0m - Generated the fake IAT at 0xe20000, size=0x3d0
> ←[1;32mINFO←[0m - Patching call and jmp sites ...
> ←[1;32mINFO←[0m - Dumping PE with OEP=0x43ef4f ...
> ←[1;32mINFO←[0m - Fixing dump ...
> ←[1;32mINFO←[0m - Output file has been saved at unpacked_VBAPass.exe

Here's the target file: [target file](https://href.li/?https://www.thegrideon.com/download/vbnoinst.zip)

**Comment by samis2613** [comment]
Were you ever able to resolve this? I'm having the same issue but with a different target file.

**Comment by ergrelet** [comment]
Hi!

Sorry about the delayed response. This "error" message is actually misleading as it may happen in case where the dumping is successful. From the look of your log, it looks like the dumping went fine in your case (many imports resolved and the dump fix went through).

I'll this "demote" this log to `DEBUG` as it's obviously not useful as an `ERROR` in itself.

**Comment by ergrelet** [comment]
"Fix" is now on `main`, I'm closing this issue.
