### ISSUE TITLE
Unable to find OEP of .NET WPF programs for a long time

### ISSUE THREAD

**Issue by ghost** [ergrelet/unlicense#52]
The program I need to unpack is a .NET WPF program, and it protects winlicense2.0-2.4.6 and uses Babel's confusion, but unlicense can't find the OEP of this program for a long time, even if the timeout is set.
Log:
PS C:\Users\[Protected]\Desktop> .\unlicense_x32.exe "C:\Program Files (x86)\Netease\MCLauncher\WPFLauncher.exe"
INFO - Detected packer version: 2.x
frida-agent: Setting up OEP tracing for "WPFLauncher.exe"
frida-agent: Exception handler registered
ERROR - Original entry point wasn't reached before timeout
[WPFLauncher.zip](https://github.com/ergrelet/unlicense/files/9556922/WPFLauncher.zip)

**Comment by redxhawk** [comment]
For the older versions of Themida/Winlicense just run and dump the exe through Extreme Dumper or any memory dumper.

**Comment by ergrelet** [comment]
Hi! I cannot reproduce the issue. The OEP is properly found with v0.3.0 on my side.
