### ISSUE TITLE
ERROR - Target PE cannot be dumped with this interpreter. This is most likely a 32 vs 64 bit mismatch.

### ISSUE THREAD

**Issue by Zibri** [ergrelet/unlicense#54]
ERROR - Target PE cannot be dumped with this interpreter. This is most likely a 32 vs 64 bit mismatch.

**Comment by Zibri** [comment]
I have a themida obfuscated DLL... it seems 32 bit...
would be nice to unpack it and reverse it...
but I get that error...

**Comment by Zibri** [comment]
The 64 bit version gives that error... while the 32 bit version says:

pyinstaller-win32>unlicense ..\Xiaomi_Official_Tool_P_A_S_3030\Sla_Challenge.dll
INFO - Detected packer version: 3.x
frida-agent: Setting up OEP tracing for "unknown.dll"
frida-agent: Target module has been loaded (thread #12080) ...
frida-agent: Exception handler registered
frida-agent: OEP found (thread #12080): 0x646be9e5
INFO - OEP reached: OEP=0x646be9e5 BASE=0x64580000 DOTNET=False

and then sits there

**Comment by LabGuy94** [comment]
It might take a while to run, just wait a while
