### ISSUE TITLE
ERROR - Failed to automatically detect packer version

### ISSUE THREAD

**Issue by tooBugs** [ergrelet/unlicense#57]
![thmida](https://user-images.githubusercontent.com/8829963/196015353-cd4bb845-13e3-46a7-99cf-9d3e9d48b94f.png)
Hello, When I pack the PE, I don't check these three items，and then unpack use unlicense.exe ,this tool tip “Failed to automatically detect packer version”  ,Is this supported? thank you!

**Comment by tooBugs** [comment]
thank you fixing, thanks very much

**Comment by mysamed** [comment]
hello i have the same problem, i am waiting for the current fix exe file to be compiled, thank you

**Comment by ergrelet** [comment]
I'll close this as it's now fixed on the `main` branch I think.
