### ISSUE TITLE
ERROR: No matching distribution found for pyscylla<0.12.0,>=0.11.0

### ISSUE THREAD

**Issue by kumaraguru1735** [ergrelet/unlicense#60]
pip install git+https://github.com/ergrelet/unlicense.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/ergrelet/unlicense.git
Cloning https://github.com/ergrelet/unlicense.git to /tmp/pip-req-build-5biwaliz
Running command git clone --filter=blob:none --quiet https://github.com/ergrelet/unlicense.git /tmp/pip-req-build-5biwaliz
Resolved https://github.com/ergrelet/unlicense.git to commit 217d0d66c57b5deae45f8abd05c851a0bb3b0e6e
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done
Collecting unicorn<2.0,>=1.0
Downloading unicorn-1.0.3-py2.py3-none-manylinux1_x86_64.whl (8.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 2.6 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement pyscylla<0.12.0,>=0.11.0 (from unlicense) (fromversions: none)
ERROR: No matching distribution found for pyscylla<0.12.0,>=0.11.0

**Comment by ergrelet** [comment]
Hi!

I guess you're running Python 3.11 😊  
This version isn't yet supported but I plan on adding support for that version soon (as it brings many improvements).

**Comment by kumaraguru1735** [comment]
It work on python 2.x ??

**Comment by ergrelet** [comment]
No, sorry it wasn't clear, supported Python versions are currently: `3.9` and `3.10`.

**Comment by kumaraguru1735** [comment]
╭─agent17@agent17 in ~ as 🧙 took 3ms
╰─λ python3 -m pip install git+https://github.com/ergrelet/unlicense.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/ergrelet/unlicense.git
Cloning https://github.com/ergrelet/unlicense.git to /tmp/pip-req-build-pkm2_mim
Running command git clone --filter=blob:none --quiet https://github.com/ergrelet/unlicense.git /tmp/pip-req-build-pkm2_mim
Resolved https://github.com/ergrelet/unlicense.git to commit 217d0d66c57b5deae45f8abd05c851a0bb3b0e6e
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done
Collecting lief>=0.12.2
Using cached lief-0.12.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.1 MB)
ERROR: Could not find a version that satisfies the requirement pyscylla<0.12.0,>=0.11.0 (from unlicense) (fromversions: none)
ERROR: No matching distribution found for pyscylla<0.12.0,>=0.11.0

╭─agent17@agent17 in ~ as 🧙 took 5s
[🔴] × python --version
Python 3.10.8
