### ISSUE TITLE
frida.ProcessNotRespondingError

### ISSUE THREAD

**Issue by ConnorDoesDev** [ergrelet/unlicense#63]
Hi, after executing `unlicense app.exe --verbose`, I get the following error:
```frida.ProcessNotRespondingError: process with pid 1356 either refused to load frida-agent, or terminated during injection```
It successfully detects the packer version, but stops almost right after that.

**Comment by Purarity** [comment]
Hello, any update on this?

**Comment by ergrelet** [comment]
Hi! This is mostly likely due to the fact that the executable fails to start because of missing dependencies.
