### ISSUE TITLE
Can NOT work

### ISSUE THREAD

**Issue by peter8777555** [ergrelet/unlicense#67]
File :
https://www.mediafire.com/file/qbn11xakj3d6c97/TEST.7z/file
OS:
Windows 7 X64.

C:\TEST>unlicense LINE.exe
INFO - Detected packer version: 2.x
frida-agent: Setting up OEP tracing for "LINE.exe"
frida-agent: Exception handler registered
frida-agent: OEP found (thread #11108): 0x2142a76
INFO - OEP reached: OEP=0x2142a76 BASE=0x1020000 DOTNET=False

This is all messages.

**Comment by ergrelet** [comment]
Hi! I'd advise against using Windows 7 to run `unlicense` as several dependencies might not support that Windows version anymore.
