### ISSUE TITLE
(frida:8320): GLib-GIO-WARNING **: 03:15:49.172: _g_dbus_worker_do_read_cb: error determining bytes needed: Blob indicates that message exceeds maximum message length (128MiB)

### ISSUE THREAD

**Issue by crack3n** [ergrelet/unlicense#7]
Getting this message when i want to unlicense x32 executable
![Screenshot 2021-12-17 031813](https://user-images.githubusercontent.com/53404805/146463039-a81be104-f81c-4da4-ba8f-709f3855b957.png)

**Comment by ergrelet** [comment]
@crack3n This issue should be fixed with the latest commit.
