### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ItsEnesN** [ergrelet/unlicense#70]
I dont know what this means but anyway
![image](https://user-images.githubusercontent.com/76757293/205663679-97204469-34f6-46dd-8b91-1f9b57395d4b.png)
I use the version from the "releases" Tab.

**Comment by greenozon** [comment]
Your log shown error 0x2e4 -> "The requested operation requires elevation."

have you tried to do the process under admin level?

**Comment by ItsEnesN** [comment]
> greenozon

ups thanks
