### ISSUE TITLE
Is it support for unity exe?

### ISSUE THREAD

**Issue by PaienNate** [ergrelet/unlicense#72]
Have some try for a unity exe but failed. 
It said:ERROR - Failed to automatically detect packer version
Use Detect It easy to see:

![image](https://user-images.githubusercontent.com/68044286/212533487-63696568-f77d-4dd6-882b-f89b8b69652c.png)

Then add target version:

--target_version=3

log is that:

INFO - Detected packer version: 3.x

ERROR - Failed to automatically detect .text section

And sample is here:
[DaveTheDiver.zip](https://github.com/ergrelet/unlicense/files/10419859/DaveTheDiver.zip)

I am not sure if I have something wrong? As it is a unity exe...?

**Comment by ergrelet** [comment]
Hi! This bug is fixed on the `main` branch
