### ISSUE TITLE
RESOURCE_TABLE is empty

### ISSUE THREAD

**Issue by Shemdy** [ergrelet/unlicense#73]
![image](https://user-images.githubusercontent.com/114173372/218238341-14fecb6d-049c-4616-8d6b-20d32f231ba6.png)
Good evening! When trying to rebuild a file, an error occurs at the *_resolve_section_names* stage; after slightly changing the script, I found out that the reason for this was the condition that checks whether the resource_table is empty. Otherwise, he just breaks the build.
![image](https://user-images.githubusercontent.com/114173372/218238449-ae5622d6-bbe9-4123-81ef-18eec8dd3e2e.png)
Here is a link to the file that I am trying to decompile, I am her squirrel in this and am not aware of all aspects - https://www.sendspace.com/file/0urzun .

**Comment by ergrelet** [comment]
Hi! This issue has been fixed on the `main` branch
