### ISSUE TITLE
ERROR - IAT not found

### ISSUE THREAD

**Issue by illegal-instruction-co** [ergrelet/unlicense#74]
```
INFO - Detected packer version: 3.x
frida-agent: Setting up OEP tracing for "blabla.exe"
frida-agent: Exception handler registered
frida-agent: OEP found (thread #12108): 0xANADDR
INFO - OEP reached: OEP=0xOEP BASE=0xANADDRDOTNET=False
INFO - Using given OEP RVA value instead (0x1)
ERROR - IAT not found
```

i am ready to share binary on email.

**Comment by ergrelet** [comment]
Hi! I've pushed a fix on `dev` that might solve your issue, if you have time to check it out.

**Comment by illegal-instruction-co** [comment]
> Hi! I've pushed a fix on `dev` that might solve your issue, if you have time to check it out.

Thank you, works.

**Comment by ergrelet** [comment]
Perfect, glad to hear that 👍
I'm closing this issue then
