### ISSUE TITLE
dll Make a mistake,Missing entry:#0

### ISSUE THREAD

**Issue by xiu-shen** [ergrelet/unlicense#77]
pip install git+https://github.com/ergrelet/unlicense.git

INFO - Detected packer version: 3.x
frida-agent: Setting up OEP tracing for "hasp_windows_x64_50590.dll"
frida-agent: Target module has been loaded (thread #21016) ...
frida-agent: Exception handler registered
frida-agent: OEP found (thread #21016): 0x23658e0
INFO - OEP reached: OEP=0x23658e0 BASE=0x2000000 DOTNET=False
INFO - IAT found: 0x2370000
INFO - Resolving imports ...
INFO - Imports resolved: 141
INFO - Fixed IAT at 0x2370000, size=0x480
INFO - Dumping PE with OEP=0x23658e0 ...
INFO - Fixing dump ...

C:\Users\Ad\Desktop\1\windows_x64_50590.dll   Make a mistake,Missing entry:#0

**Comment by ergrelet** [comment]
Hi! Looks like the unpack was successful but you received an error popup from `rundll32.exe`? It should be fine though.

**Comment by xiu-shen** [comment]
Thank you for your reply. 
The unpacked program cannot be used.
with your previous unlicense 3.0 you could unlock some programs, but some programs show No section associated with the data directory 'RESOURCE_TABLE'.
But the latest code has never been successful since it was installed. I guess it has something to do with my installation environment or packaging method. Could you release the latest unlicense.exe file when you have time?
Thank you very much for your help

**Comment by ergrelet** [comment]
Alright. Unpacked program can generally not be run as is indeed, `unlicense` is more targeted at reverse engineers right now, but I'd like to make unpacked executables runnable in the future.  
I understand installing `unlicense` from source isn't easy for everyone, I'm planning to release a new version with several fixes including those already on `main`/`dev` soon enough.

**Comment by xiu-shen** [comment]
Thank you very much for doing this program, looking forward to your new version

**Comment by xiu-shen** [comment]
Hello, I am trying to package the source code, this is my packaging step
1. C:\Users\123>git clone https://github.com/ergrelet/unlicense.git
2. C:\Users\123>pip install unlicense/
3. C:\Users\123\unlicense>poetry install
4. C:\Users\123\unlicense>poetry run pyinstaller unlicense.spec
Could you check it for me? Thank you
Thank you very much for doing this program, looking forward to your new version

**Comment by xiu-shen** [comment]
The installation of the 32-bit exe was successful using the above method

After installing python-64 bit, I tried to package the unlicense64 bit exe file and the following error occurred

C:\Users\123\unlicense>poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: unlicense (0.3.0)

C:\Users\123\unlicense>poetry run pyinstaller unlicense.spec
273 INFO: PyInstaller: 5.13.0
273 INFO: Python: 3.11.0
280 INFO: Platform: Windows-10-10.0.22621-SP0
289 INFO: Extending PYTHONPATH with paths
['C:\\Users\\123\\unlicense']
499 INFO: Appending 'binaries' from .spec
500 INFO: Appending 'datas' from .spec
502 INFO: checking Analysis
507 INFO: Building because _input_datas changed
507 INFO: Initializing module dependency graph...
508 INFO: Caching module graph hooks...
520 INFO: Analyzing base_library.zip ...
1764 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
1969 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
3213 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
4813 INFO: Caching module dependency graph...
4902 INFO: running Analysis Analysis-00.toc
4905 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by D:\Python\32\python.exe
4976 INFO: Analyzing C:\Users\123\unlicense\unlicense\__main__.py
5226 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
5332 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
5787 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
6084 INFO: Processing pre-safe import module hook distutils from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-distutils.py'.
6085 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
6307 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
6328 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
6430 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
7325 INFO: Processing module hooks...
7339 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
8420 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
9371 INFO: Loading module hook 'hook-platformdirs.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
9583 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
9921 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks'...
10358 INFO: Looking for ctypes DLLs
10435 INFO: Analyzing run-time hooks ...
10438 INFO: Including run-time hook 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
10439 INFO: Including run-time hook 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
10443 INFO: Including run-time hook 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
10445 INFO: Including run-time hook 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_setuptools.py'
10446 INFO: Including run-time hook 'C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
10454 INFO: Looking for dynamic libraries

***
Failed to load the Frida native extension: DLL load failed while importing _frida: %1 不是有效的 Win32 应用程序。
Please ensure that the extension was compiled correctly
***

334 INFO: Extra DLL search directories (AddDllDirectory): []
335 INFO: Extra DLL search directories (PATH): ['C:\\Users\\123\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\unlicense-PJcfyqs_-py3.11\\Scripts', 'D:\\Python\\32\\Scripts\\', 'D:\\Python\\32\\', 'D:\\Python\\32\\Scripts', 'D:\\Python\\32', 'D:\\Python\\64\\Scripts', 'D:\\Python\\64', 'D:\\Python\\Scripts', 'D:\\Python', 'D:\\VM\\bin', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0', 'C:\\WINDOWS\\System32\\OpenSSH', 'D:\\Matlab\\runtime\\win64', 'D:\\Matlab\\polyspace\\bin', 'D:\\Python\\Git\\Git\\cmd', 'C:\\Users\\123\\AppData\\Roaming\\Python\\Scripts', 'D:\\Matlab\\bin', 'C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\', 'D:\\傲梅轻松备份\\AOMEI\\AOMEI Backupper\\6.9.1', 'C:\\Users\\123\\AppData\\Local\\Microsoft\\WindowsApps', 'D:\\Python\\pycharm\\PyCharm Community Edition 2022.3.3\\bin', 'c:\\users\\123\\.local\\bin']
11316 INFO: Looking for eggs
11317 INFO: Using Python library D:\Python\32\python311.dll
11317 INFO: Found binding redirects:
[]
11320 INFO: Warnings written to C:\Users\123\unlicense\build\unlicense\warn-unlicense.txt
11362 INFO: Graph cross-reference written to C:\Users\123\unlicense\build\unlicense\xref-unlicense.html
11372 INFO: checking PYZ
11400 INFO: checking PKG
11401 INFO: Building because toc changed
11401 INFO: Building PKG (CArchive) unlicense.pkg
18087 INFO: Building PKG (CArchive) unlicense.pkg completed successfully.
18089 INFO: Bootloader C:\Users\123\AppData\Local\pypoetry\Cache\virtualenvs\unlicense-PJcfyqs_-py3.11\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
18089 INFO: checking EXE
18089 INFO: Building EXE because EXE-00.toc is non existent
18089 INFO: Building EXE from EXE-00.toc
Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. For more details and instructions how to build the bootloader see
<https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html>

What should I do about it? thank you

**Comment by xiu-shen** [comment]
May I ask if this warning has any effect

INFO - Detected packer version: 3.x
frida-agent: Setting up OEP tracing for "hasp_windows_x64_50590.dll"
frida-agent: Target module has been loaded (thread #18648) ...
frida-agent: Exception handler registered
frida-agent: OEP found (thread #18648): 0x23658e0
INFO - OEP reached: OEP=0x23658e0 BASE=0x2000000 DOTNET=False
INFO - Looking for the IAT...
INFO - Performing linear scan in data sections...
INFO - IAT found: 0x2370000-0x24a17c5
INFO - Resolving imports ...
**_WARNING - A resolved API wasn't an export, it's been replaced with 'kernel32.ExitProcess'._**
INFO - Imports resolved: 141
INFO - Fixed IAT at 0x2370000, size=0x471
INFO - Dumping PE with OEP=0x23658e0 ...
INFO - Fixing dump ...
INFO - Rebuilding PE ...
INFO - Output file has been saved at 'unpacked_hasp_windows_x64_50590.dll'

**Comment by ergrelet** [comment]
> May I ask if this warning has any effect
> 
> INFO - Detected packer version: 3.x frida-agent: Setting up OEP tracing for "hasp_windows_x64_50590.dll" frida-agent: Target module has been loaded (thread #18648) ... frida-agent: Exception handler registered frida-agent: OEP found (thread #18648): 0x23658e0 INFO - OEP reached: OEP=0x23658e0 BASE=0x2000000 DOTNET=False INFO - Looking for the IAT... INFO - Performing linear scan in data sections... INFO - IAT found: 0x2370000-0x24a17c5 INFO - Resolving imports ... **_WARNING - A resolved API wasn't an export, it's been replaced with 'kernel32.ExitProcess'._** INFO - Imports resolved: 141 INFO - Fixed IAT at 0x2370000, size=0x471 INFO - Dumping PE with OEP=0x23658e0 ... INFO - Fixing dump ... INFO - Rebuilding PE ... INFO - Output file has been saved at 'unpacked_hasp_windows_x64_50590.dll'

Looks like the dumping went fine. The warning is here just in case something looks fishy during the static analysis but in general, if there are only one of those during your dump then it should be fine 👍

**Comment by ergrelet** [comment]
I'm closing this issue since you re-opened one for the remaining issue you have (#96).
