### ISSUE TITLE
Why is it possible to dump 32-bit programs successfully using the 64-bit python interpreter?

### ISSUE THREAD

**Issue by OrientalGlass** [ergrelet/unlicense#78]
It is possible to run a 32-bit unlicense without a 32-bit python interpreter

**Comment by ergrelet** [comment]
Hi, I'm not sure I understand your question. When you say 32-bit `unlicense`, do you mean the executable available in the releases? If so, no you don't need any interpreter installed when using `unlicense.exe`.

**Comment by ergrelet** [comment]
I'll close this issue. If you want to discuss that, feel free to comment and I'll reopen the issue.
