### ISSUE TITLE
how to install it and use it

### ISSUE THREAD

**Issue by architect-ghpython** [ergrelet/unlicense#8]
hello,I don't know how to install it. a  python package needs setup.py。so I  have created setup.py

- import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="unlicense",
    version="0.0.1",
    author="ken",
    author_email="xxxxx@gmail.com",
    description="Image kernel.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/kenblikylee/imgkernel",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)
and do the python setup.py  install   command

but i don't know how to use it ?

**Comment by ergrelet** [comment]
Hi!

Sorry I'm not sure I understand why you used a `setup.py` file from another Python package here?
`unlicense` uses a `pyproject.toml` file (PEP 518) which is enough for you to install the package, as described in the README:
```
$ git clone https://github.com/ergrelet/unlicense.git
$ python install unlicense/
```
Have you tried executing the above command lines?

If you still need to use a `setup.py` file for some reason, you try with the following:
```python
import setuptools

setuptools.setup()
```

**Comment by GUANCAIBAN** [comment]
Sorry,I am a learner.I used to executing the above command lines.
And then how can I use the tool?I execute tcommand as followed:
`python unlicense --help`
but it's error:[Errno 2] No such file or directory
Could you tell me how to used this?

**Comment by ergrelet** [comment]
@GUANCAIBAN Hi, if the above commands (most importantly `pip install unlicense`) succeeded, you should be able to use the tool like so: `unlicense --help`.
