### ISSUE TITLE
Issues when installing unlicense

### ISSUE THREAD

**Issue by fabek** [ergrelet/unlicense#82]
C:\Users\Administrator\Desktop\unlicense>pip install git+https://github.com/ergrelet/unlicense.git
Collecting git+https://github.com/ergrelet/unlicense.git
  Cloning https://github.com/ergrelet/unlicense.git to c:\users\administrator\appdata\local\temp\pip-req-build-ikd5o92l
  Running command git clone --filter=blob:none --quiet https://github.com/ergrelet/unlicense.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-ikd5o92l'
  Resolved https://github.com/ergrelet/unlicense.git to commit 217d0d66c57b5deae45f8abd05c851a0bb3b0e6e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting capstone<5.0,>=4.0 (from unlicense==0.3.0)
  Downloading capstone-4.0.2-py2.py3-none-win_amd64.whl (896 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 896.4/896.4 kB 3.8 MB/s eta 0:00:00
Collecting fire<0.5,>=0.4 (from unlicense==0.3.0)
  Downloading fire-0.4.0.tar.gz (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.7/87.7 kB ? eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting frida<16.0,>=15.1 (from unlicense==0.3.0)
  Downloading frida-15.2.2.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting lief>=0.12.2 (from unlicense==0.3.0)
  Downloading lief-0.13.0-cp311-cp311-win_amd64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 22.0 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of unlicense to determine which version is compatible with other requirements. This could take a while.
**ERROR: Could not find a version that satisfies the requirement pyscylla<0.12.0,>=0.11.0 (from unlicense) (from versions: none)
ERROR: No matching distribution found for pyscylla<0.12.0,>=0.11.0**

[notice] A new release of pip is available: 23.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Users\Administrator\Desktop\unlicense>pip install pyscylla
**ERROR: Could not find a version that satisfies the requirement pyscylla (from versions: none)
ERROR: No matching distribution found for pyscylla**

[notice] A new release of pip is available: 23.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by alexrp** [comment]
This is because pyscylla and unlicense only work on Python 3.10. pip is just giving an extremely unhelpful error message.

**Comment by ergrelet** [comment]
This is fixed with https://github.com/ergrelet/unlicense/commit/12d9ea6755a75037694a594e7006001a291cf839 (and `pyscylla` 0.11.1).
