### ISSUE TITLE
ERROR - IAT not found

### ISSUE THREAD

**Issue by zhuimengqq** [ergrelet/unlicense#83]
[1;32mINFO[0m - Detected packer version: 3.x
[1;36mfrida-agent[0m: Setting up OEP tracing for "test.exe"
[1;36mfrida-agent[0m: Exception handler registered
[1;36mfrida-agent[0m: OEP found (thread #8492): 0x14629b4
[1;32mINFO[0m - OEP reached: OEP=0x14629b4 BASE=0x400000 DOTNET=False
[31;20mERROR - IAT not found[0m
[test.zip](https://github.com/ergrelet/unlicense/files/11533654/test.zip)

**Comment by ergrelet** [comment]
Hi! I've pushed a fix on the `dev` branch, check it out.
