### ISSUE TITLE
error when opening unlicense

### ISSUE THREAD

**Issue by thevitaluk** [ergrelet/unlicense#86]
the function received no value for the required argument: pe_to_dump
usage: unlicense.exe PE_TO_DUMP <flags>

Please can you help?

**Comment by greenozon** [comment]
Please add some screens with the issue as well as your input binary

**Comment by ergrelet** [comment]
Hi! You need to provide the path to the PE file to unpack as a command-line argument:
`unlicense.exe .\path\to\the\pe_to_dump.exe`
