### ISSUE TITLE
Themida's "Advanced API Wrapping"

### ISSUE THREAD

**Issue by h5kk** [ergrelet/unlicense#89]
Running unlicense on an exe that used to work almost flawlessly before 

However, doing so on a newer version has two major issues:

- It's missing imports
- Api calls addresses are wrong

Could it be because of the Themida setting below? Is there a way to fix it? 

![image](https://github.com/ergrelet/unlicense/assets/31630310/927a0012-ed33-42d3-88c0-2f10290e276c)

**Comment by ergrelet** [comment]
Hi, what version of Themida is it? 3.1.4.0?

**Comment by h5kk** [comment]
> Hi, what version of Themida is it? 3.1.4.0?

Not sure what version the exe is packed with. Will experiment with different Themida versions and try to make a guess. Can also send you the exe in question if it would help.

**Comment by ergrelet** [comment]
Alright, I've pushed a small fix on the `dev` branch, you can test it out and tell me if it fixes your issue
