### ISSUE TITLE
does not install, and does not run

### ISSUE THREAD

**Issue by gorongolydev** [ergrelet/unlicense#9]
How to install it, because I run the commands, next it downloads perfect but it never installs or runs because it does not see the dependencies please update and perfect the installation method, it does not work $ git clone https://github.com/ergrelet/unlicense .git
 $ pip install unlicense /

**Comment by ergrelet** [comment]
Hi!

What OS are you running on and what's your Python interpreter version? Also the exact error message would help.

This project is meant to be run on Windows, although I reckon it's not explicitly indicating in the README.
