### ISSUE TITLE
There was a problem packing

### ISSUE THREAD

**Issue by xiu-shen** [ergrelet/unlicense#96]
I used 64-bit python3.11 to package the unlicense and the following error occurred

Failed to load the Frida native extension: DLL load failed while importing _frida: %1 Not a valid Win32 application.
Please ensure that the extension was compiled correctly

**Comment by ergrelet** [comment]
Hi! I guess this is the same error you mentioned in your other issue #77. I'm not sure what's happening here but it sounds like a 64-bit vs 32-bit mismatch between the dependencies and the target PyInstaller build.  
FYI I'll certainly release version 0.4.0 today.

**Comment by xiu-shen** [comment]
Thank you very much for releasing unlicense 0.4.0, which has successfully solved my problem. 

My sincere thanks to you again
