### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by ItsProfessional** [ergrelet/unlicense#98]
DLL: https://gofile.io/d/F48nPJ

I get this error when trying to use unlicense on that dll.
The dll is a hook dll for a game. When normally injecting the dll into the game, I don't get this error, so I don't think this is a problem with the dll.

![image](https://github.com/ergrelet/unlicense/assets/63961221/9d4fea85-53ca-426e-9ca3-d6fa8f1912da)

**Comment by ergrelet** [comment]
Hi!  
I believe this a very unclear way for `rundll32` to say that a dependency of `hackpro.dll` hasn't been found.  
You need to make sure the DLL can be loaded properly by `rundll32`, so from what you said, I think you should try from the game's directory, where the needed dependencies might be located.

**Comment by ItsProfessional** [comment]
That worked, thanks.
